### ISSUE TITLE
不建议在library中有任务toast显示

### ISSUE THREAD

**Issue by henjue** [pengjianbo/GalleryFinal#13]
如果。目前如果拍照失败或显示toast，建议返回给调用着，由调用调用着自己处理失败时间，另外提交一个pull request，拍照是按下返回键问题

**Comment by pengjianbo** [comment]
谢谢你的意见。新版我会改善你说的问题。

**Comment by pengjianbo** [comment]
拍照是按下返回键问题。可以说具体点吗？是不是拍照按下返回键提示拍照失败，回调错误信息给调用者？

**Comment by pengjianbo** [comment]
明白了，谢谢~

**Comment by henjue** [comment]
对的就是那个意思。library不建议去干预library自身之外的任何视觉上的东西，哈哈。我觉得可以把各种状态返回给调用着，比如：
```java
static final int RESULT_SUCCESS=0x0;
static final int RESULT_TAKE_FAILD=0x1;
static final int RESULT_CROP_FAILD=0x2;
....
....
switch(code){
case RESULT_TAKE_FAILD:
//这个时候开发着会去提示，同时干一些他自己的逻辑
break;
case RESULT_CROP_FAILD:
//此错误可能开发者不需要任何提示
break;
}
```
总之我的建议就是尽量告诉开发者结果，library本身不做任何多余的处理，有点啰嗦。不好意思

**Comment by pengjianbo** [comment]
嗯。明白你的意思。我是想让开发者使用起来比较简单，所有的复杂的逻辑都交给了框架，对于开发者只需要关心拿到的图片和错误信息，就像小白用户可以很快速的入手，同时又想满足大家不同的需求，一心想框架功能做全做强大。哈哈~也许自己考虑太多了。非常感谢你意见和看法.

**Comment by henjue** [comment]
@pengjianbo 你可以提供另一个library来作为它人补充用于提供默认Simple实现,就像retrofit 2.0人各个convert一样。我觉得这样不错。
