### ISSUE TITLE
安卓4.4 透明顶部状态栏及底部导航条错位问题

### ISSUE THREAD

**Issue by bf3400** [pengjianbo/GalleryFinal#14]
![image](https://cloud.githubusercontent.com/assets/5080247/12298088/44e57780-ba4b-11e5-94d7-5c598fa06c7a.png)

布局的标题顶上去了...
activity布局中没有写... android:fitsSystemWindows="true"

**Comment by bf3400** [comment]
替换了布局文件效果

![image](https://cloud.githubusercontent.com/assets/5080247/12298434/0fc00514-ba4d-11e5-8a8a-972f1970b9a1.png)

**Comment by pengjianbo** [comment]
这个应该是你设置主题引起的吧。可以贴一下你主题代码吗？

**Comment by bf3400** [comment]
![image](https://cloud.githubusercontent.com/assets/5080247/12381847/1c6c9b14-bdcd-11e5-8873-44ae87f91b08.png)
![image](https://cloud.githubusercontent.com/assets/5080247/12381860/371013ce-bdcd-11e5-8e42-437ba55dc608.png)

**Comment by bf3400** [comment]
android:fitsSystemWindows="true"
我在你的act布局加了这句

**Comment by pengjianbo** [comment]
是的，由于你设置主题的原因，是要在root布局上加android:fitsSystemWindows="true"。

**Comment by bf3400** [comment]
图片编辑时, 顶部状态栏 不支持沉浸式布局, 是因为什么原因呢?

![image](https://cloud.githubusercontent.com/assets/5080247/12387865/69ca3794-be0a-11e5-82aa-5465a6515301.png)
