### ISSUE TITLE
图片不能重复选择

### ISSUE THREAD

**Issue by hush881025** [pengjianbo/GalleryFinal#17]
现在图片可以重复选择，这个能加进去吗

**Comment by pengjianbo** [comment]
可以通过过滤方法过滤已选图片，README.md文件里面有说明~

**Comment by cyq7on** [comment]
setSelected(List)，setFilter(List list)这两个方法都不起作用，但是lz的demo确实是正常的，不解

**Comment by pengjianbo** [comment]
setFilter是过滤，不会再相册中出现，setSelected是会在相册中出现，默认是选中的。两个方法不能同时存在

**Comment by cyq7on** [comment]
我知道啊，我就是单独用的一个，结果都不起作用

**Comment by ydcool** [comment]
遇到了同样的问题，`setSeletced()` 方法无效, 但是 demo 中是有效的。。好诡异的问题
