### ISSUE TITLE
在三星SM-N9005型号上照相机问题

### ISSUE THREAD

**Issue by gdmec07120730** [pengjianbo/GalleryFinal#19]
打开相册里面的那个照相机在三星SM-N9005上拍完照保存时会出现take photo failure

**Comment by pengjianbo** [comment]
偶尔出现还是每次都会这样？

**Comment by gdmec07120730** [comment]
拍照基本每次都这样，几乎不能成功回调照片

**Comment by pengjianbo** [comment]
你使用的哪个版本？

**Comment by gdmec07120730** [comment]
compile 'cn.finalteam:galleryfinal:1.4.6' 我用的就是这个噢，加上我还特意下载这源码来跑了一下，还是一样的情况，不过在点击拍照的就有时候可以，在打开相册里面的拍照就退出相机提示take photo failure

**Comment by pengjianbo** [comment]
好，我这边查一下

**Comment by gdmec07120730** [comment]
OK，Thanks

**Comment by pengjianbo** [comment]
你好~提交了新版本：compile 'cn.finalteam:galleryfinal:1.4.7'
可能是因为有些手机拍照的时Activity会重启，从而导致Activity的数据丢失了. http://www.07net01.com/2015/09/924147.html。
麻烦更新到最新版本，如再有问题及时反馈。谢谢

**Comment by gdmec07120730** [comment]
现在没问题了。谢谢啦，处理的好快呀，给作者点个赞

**Comment by pengjianbo** [comment]
解决了就好。呵呵~谢谢夸奖
