### ISSUE TITLE
Imagloader，功能独立

### ISSUE THREAD

**Issue by cyq7on** [pengjianbo/GalleryFinal#20]
1、UniversalImagloader也算主流吧
2、希望新版本也能保持相册、拍照、裁剪和图片编辑功能可独立使用

**Comment by pengjianbo** [comment]
1、现在很多人使用的Imageloader都不一样。UniversalImagloader和picasso都是很老的框架，老用户会多一些，不过现在glide和fresco有很多的有点，也有很多人慢慢迁移过来了。
2、现在相册、拍照、裁剪和图片编辑已经是独立使用的。

**Comment by cyq7on** [comment]
哦，好得，谢谢lz

**Comment by cyq7on** [comment]
哦，好得，谢谢lz

**Comment by cyq7on** [comment]
哦，好得，谢谢lz

**Comment by cyq7on** [comment]
哦，好得，谢谢lz
