### ISSUE TITLE
SDK版本22可以用吗

### ISSUE THREAD

**Issue by GodSpeed-** [pengjianbo/GalleryFinal#21]
项目需要，只能用SDK22，请问还可以用GalleryFinal吗

**Comment by pengjianbo** [comment]
因为GalleryFinal使用23编译的，v4包也是用的23.如果你需要22可以clone源码到项目中做一下小修改就可以了。不过因为GalleryFinal实现了对6.0系统的兼容性个人建议还是更新到23比较妥当。

**Comment by GodSpeed-** [comment]
使用了一个第三方的SDK，不支持23。。。我自己修改一下吧，谢谢
