### ISSUE TITLE
配置有点略繁琐，不知道能不能更简洁一点。

### ISSUE THREAD

**Issue by whyalwaysmea** [pengjianbo/GalleryFinal#25]

**Comment by pengjianbo** [comment]
谢谢，我再精简下吧

**Comment by whyalwaysmea** [comment]
将Readme中的使用步骤写得更傻瓜一点，会吸引更多的人使用。比如哪句话初始化，哪些语句打开相册，打开相机，又怎么获取到选择结果之类这样。配置的化只用配置一个ImageLoader。那些个性化的配置再放到后面介绍。
可能因为我是新手，所以会这样想。请多指教

**Comment by pengjianbo** [comment]
非常感谢你的建议，我会尽可能的去简化.
