### ISSUE TITLE
多选的返回的List的顺序和选择时不一致

### ISSUE THREAD

**Issue by TanTan-TT** [pengjianbo/GalleryFinal#26]
```java
ArrayList<PhotoInfo> photoList = new ArrayList<>(mSelectPhotoMap.values());
```
这句话会导致顺序不一致吧

**Comment by pengjianbo** [comment]
谢谢提醒

**Comment by wilsonssss** [comment]
resolved via "mSelectPhotoMap = new LinkedHashMap<>();"

**Comment by pengjianbo** [comment]
@wilsonssss  Thank you!

**Comment by TanTan-TT** [comment]
您好，什么时候发下一版

**Comment by pengjianbo** [comment]
@TanTan-TT 现在正在写了。由于下版需求有点多，包括UI的一些改动，估计要到2月份末-3月份初的样子才能出来。你提的List顺序不一致问题现已解决，github上切换到devlop分支即可看到

**Comment by 932236581** [comment]
您好 不知道  1.4.8.7 这个问题解决了没有。 这边需求测到有这样的问题。

**Comment by TanTan-TT** [comment]
@932236581 你好，我后来换了控件，就没有再测试

**Comment by 932236581** [comment]
https://github.com/932236581啊

**Comment by 932236581** [comment]
@TanTan-TT   你好。 就是有什么好的图片选择器 好介绍吗。 我估计要换 得重新测试了

**Comment by TanTan-TT** [comment]
@932236581 你是原生Android吗？我没有合适的，我用的ReactNative，后来自己做了一个

**Comment by 932236581** [comment]
@TanTan-TT  是原生安卓。。 那我去博客找一下巴 谢谢了
