### ISSUE TITLE
选择的图片文件路径不正确是什么原因？

### ISSUE THREAD

**Issue by KnightUK** [pengjianbo/GalleryFinal#27]

**Comment by pengjianbo** [comment]
如果你选择或拍照后图片没有执行旋转或拍照是不会改变图片的路径

**Comment by pengjianbo** [comment]
可以通过以下两个方法设置选择裁剪是否覆盖原图
`setRotateReplaceSource(boolean//配置选择图片时是否替换原始图片，默认不替换
setCropReplaceSource(boolean)//配置裁剪图片时是否替换原始图片，默认不替换`

**Comment by KnightUK** [comment]
非常感谢，我再研究下。
