### ISSUE TITLE
如何选择照片过后自动裁剪

### ISSUE THREAD

**Issue by vipheyue** [pengjianbo/GalleryFinal#28]
现在sample都是从相册选择一张照片然后到编辑页面.可不可以 直接选一张照片就到裁剪页面??谢了!

**Comment by pengjianbo** [comment]
可以的。你需要开启强制裁剪，选择图片后直接进入裁剪页面

`setForceCrop(boolean)//启动强制裁剪功能,一进入编辑页面就开启图片裁剪，不需要用户手动点击裁剪，此功能只针对单选操作
setForceCropEdit(boolean)//在开启强制裁剪功能时是否可以对图片进行编辑（也就是是否显示旋转图标和拍照图标）
 `
