### ISSUE TITLE
有个需求好像满足不了，还是我没有找到。

### ISSUE THREAD

**Issue by w695050167** [pengjianbo/GalleryFinal#6]
选择单张图片。然后必须进行剪辑。编辑只有一个剪辑。也就是说，选择了图片之后直接进入剪辑状态。这个能实现吗？在之前版本可以。现在这个怎么不知道怎么配置了？

**Comment by pengjianbo** [comment]
1、编辑页可以只显示裁剪按钮，其他选择拍照可以隐藏，都是可配置的。见GalleryConfig类，demo中也有
2、必须裁剪这个现有的功能还没有，v1.3.0版本将会加上
3、v1.3.0将在12月21号发布
