### ISSUE TITLE
PhotoEditActivity里的空指针异常问题

### ISSUE THREAD

**Issue by blazecake** [pengjianbo/GalleryFinal#64]
![image](https://cloud.githubusercontent.com/assets/6480101/14599997/1b31bd30-058d-11e6-8a67-1498846c6169.png)

cn.finalteam.galleryfinal.PhotoEditActivity类里的存储和恢复方法中有个键不一致，会导致空指针异常。

**Comment by ByteRax** [comment]
你好，我改了之后，还是这个会空指针错误

**Comment by blazecake** [comment]
错误日志贴出来看下
