### ISSUE TITLE
不支持Fragment中的onActivityResult响应

### ISSUE THREAD

**Issue by xuhuan** [pengjianbo/GalleryFinal#7]
RT。
![image](https://cloud.githubusercontent.com/assets/1960194/11999108/598a81da-aaf1-11e5-92c1-e13055af2367.png)
应该是这个方式导致的吧。

**Comment by pengjianbo** [comment]
哦。对，没有做fragment的onActivityResult。下个版本加上。tks

**Comment by xuhuan** [comment]
顺带能否出个类似于EasyImage的方法，感觉下面的方式不错。
![image](https://cloud.githubusercontent.com/assets/1960194/11999497/76ddc9c8-aafa-11e5-9a30-df27d80cb532.png)

在handleActivityResult里直接判断了状态，这样写代码的时候可以多关注下业务逻辑。

**Comment by pengjianbo** [comment]
这样通过事件回调可能会感觉好用些，这个改动会影响比较大，GalleryFinal发大版本的时候，我会考虑这个问题.tks
