### ISSUE TITLE
参数可以全局配置

### ISSUE THREAD

**Issue by xuhuan** [pengjianbo/GalleryFinal#8]
能否弄成可以全局配置，只要配置一次即可，因为参数大部分情况下都是统一的，现在每次调用的时候都要传入配置，配置里动态的参数感觉也就Activity或者Fragment，比如下面的样子
```java
GalleryFinal.openCamera(Activity);
GalleryFinal.openCamera(Fragment);
```

**Comment by pengjianbo** [comment]
你是说GalleryConfig全局配置吗？这个不能设置全局，每个人的需求都不一样，只能说满足大部分人，如果你的配置是全局的，你可以把GalleryConfig弄成成员变量。每次启动传入启动配置还是相对合理些。

**Comment by xuhuan** [comment]
这个全局不是所有人一样，也不是指默认。
是指一个应用内，比如UIL，init的时候配置下参数，后面用到的时候都不再需要传入配置参数了，直接调用对应的方法就好了。
或者我在应用启动的时候配置一下，后面其他页面调用的时候不用再传入配置了，因为整个应用里配置基本都一样，如果个别页面需要不一样的话可以传入具体配置，不传配置的话默认调用一开始配置的参数。

**Comment by pengjianbo** [comment]
哦~你的意思是：app默认的公共配置，而不是框架的默认配置，比如开启编辑功能几乎所有的操作都需要开启，没必要每次都enableEdit。

**Comment by xuhuan** [comment]
应该算公共配置，就是对于统一的只要配置一次就行，没必要每次都传完整的配置进去，然后接口就可以用一开始说的方式，调用只需要传入Activity或者Fragment即可。当然还要保留把配置传入的接口，用于需要单独处理的地方。
